Contact Us section
GSG-FC02/PalArt-Gallery pull request #10
Opened 2021-03-02 09:02 UTC by reemsh2000

Relates #7
contact us section with style

2021-03-02 09:10 UTC, emanjaber approved these changes, later dismissed
Good job Reem! 
Keep on ^^

2021-03-03 08:58 UTC, sara219 requested changes

2021-03-03 08:58 UTC, sara219 commented on README.md
> +#PalArt-Gallery
Always upload each file with the related section and branch. 
like there, you upload the readme.md with a branch and pull-request called contact-us

delete any unrelated files to contact-us

2021-03-03 08:58 UTC, sara219 commented on index.html
> + <div class="contact-us">
use semantic element 
there's a lot of divs, try to replace them with the semantic element

2021-03-03 08:58 UTC, sara219 commented on css/style.css
> +   font-size: 30px;
pay attention to the code formatting, use prettier to format your code 

![Peek 2021-03-02 19-15](https://user-images.githubusercontent.com/47992412/109779657-d2071d00-7c0e-11eb-8870-b6bc3b6e4a92.gif)

2021-03-03 08:58 UTC, sara219 commented on css/style.css
> +    /* flex-direction: row; */
delete useless and unnecessary line

2021-03-03 08:58 UTC, sara219 commented on css/style.css
> +
add a useful comment to  tell us what is that code and the use of it ( to which section also )

2021-03-03 09:04 UTC, sara219 requested changes
make the width equal, also the colour contrast is a little bit uncomfortable 

![imageedit_4_5993238474](https://user-images.githubusercontent.com/47992412/109780753-f7485b00-7c0f-11eb-8d7f-1223ae25f83e.gif)

2021-03-03 20:53 UTC, sara219 approved these changes

2021-03-03 20:59 UTC, suhail-radwan approved these changes

2021-03-03 23:09 UTC, emanjaber approved these changes

2021-03-03 23:10 UTC, merged

2021-03-04 05:31 UTC, Heba-elLouh approved these changes