create a header with style
GSG-FC02/PalArt-Gallery pull request #11
Opened 2021-03-02 11:11 UTC by suhail-radwan

Relates #3

2021-03-02 11:21 UTC, reemsh2000 approved these changes
good job

2021-03-02 23:06 UTC, emanjaber approved these changes
good job Suhail
keep on ^^

2021-03-03 09:25 UTC, sara219 requested changes

2021-03-03 09:25 UTC, sara219 commented on index.html
> +      <div class="banner_area">
use semantic HTML element

2021-03-03 09:25 UTC, sara219 commented on css/media.css
> +    }
you forget the closing `} `for the media query

2021-03-03 09:25 UTC, sara219 commented on css/media.css
> +    text-align: center;
your media query doesn't work, it looks like this 

![Screenshot from 2021-03-03 11-21-01](https://user-images.githubusercontent.com/47992412/109783415-a5ed9b00-7c12-11eb-936e-25cb3b9c20b2.png)

2021-03-03 09:41 UTC, merged