header of the second gallery page , with about the painters section
GSG-FC02/PalArt-Gallery pull request #19
Opened 2021-03-04 12:15 UTC by reemsh2000

Relates #9

2021-03-04 16:44 UTC, Heba-elLouh requested changes

2021-03-04 16:44 UTC, Heba-elLouh commented on index.html
> +  </head>
the right file is gal.html

2021-03-05 11:33 UTC, Heba-elLouh approved these changes

2021-03-05 11:39 UTC, emanjaber approved these changes
Great Heba & Reem

2021-03-05 11:49 UTC, suhail-radwan approved these changes

2021-03-05 11:53 UTC, merged